export const PORTFOLIO_FETCH_REQUEST = "PORTFOLIO_FETCH_REQUEST";
export const PORTFOLIO_FETCH_SUCCESS = "PORTFOLIO_FETCH_SUCCESS";
export const PORTFOLIO_FETCH_FAIL = "PORTFOLIO_FETCH_FAIL";

export const PORTFOLIO_TRANSACTION_REQUEST = "PORTFOLIO_TRANSACTION_REQUEST";
export const PORTFOLIO_TRANSACTION_SUCCESS = "PORTFOLIO_TRANSACTION_SUCCESS";
export const PORTFOLIO_TRANSACTION_FAIL = "PORTFOLIO_TRANSACTION_FAIL";

export const PORTFOLIO_SELL_REQUEST = "PORTFOLIO_SELL_REQUEST";
export const PORTFOLIO_SELL_SUCCESS = "PORTFOLIO_SELL_SUCCESS";
export const PORTFOLIO_SELL_FAIL = "PORTFOLIO_SELL_FAIL";

